name: factionsZ
main: EschieEsh\factionsZ\factionsZ
version: 1.0.0
api:
- 3.0.0
- 3.0.0-ALPHA7
authors:
 - EschieEsh
description: "A faction manager plugin for MCPE"
load: STARTUP
extensions:
- sqlite3
permissions:
    faction.command:
        default: op
        children:
            faction.command.create:
                default: true
